In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
disease = pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/MultipleDiseasePrediction.csv')

In [4]:
disease.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [5]:
disease.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB


In [6]:
disease.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...  pus_filled_pimples   blackheads     scurring  \
count       4920.000000  ...         4920.000000  4920.000000  4920.000000   
mean           0.021951  ...            0.021951     0.021951     0.021951   
std            0.146539  ...            0.146539     0.146539     0.146539   
min            0.000000  ...            0.000000     0.000000     0.000000   
25%            0.000000  ...            0.000000     0.000000     0.000000   
50%            0.000000  ...            0.000000     0.000000     0.000000   
75%            0.000000  ...            0.000000     0.000000     0.000000   
max            1.000000  ...            1.000000     1.000000     1.000000   

       skin_peeling  silver_like_dusting  small_dents_in_nails  \
count   4920.000000          4920.000000           4920.000000   
mean       0.023171             0.023171              0.023171   
std        0.150461             0.150461              0.150461   
min        0.000000             0.000000              0.000000   
25%        0.000000             0.000000              0.000000   
50%        0.000000             0.000000              0.000000   
75%        0.000000             0.000000              0.000000   
max        1.000000             1.000000              1.000000   

       inflammatory_nails      blister  red_sore_around_nose  \
count         4920.000000  4920.000000           4920.000000   
mean             0.023171     0.023171              0.023171   
std              0.150461     0.150461              0.150461   
min              0.000000     0.000000              0.000000   
25%              0.000000     0.000000              0.000000   
50%              0.000000     0.000000              0.000000   
75%              0.000000     0.000000              0.000000   
max              1.000000     1.000000              1.000000   

       yellow_crust_ooze  
count        4920.000000  
mean            0.023171  
std             0.150461  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max             1.000000  

[8 rows x 132 columns]

In [7]:
disease.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [8]:
disease.shape

(4920, 133)

In [9]:
disease.corr()

itching  skin_rash  nodal_skin_eruptions  \
itching               1.000000   0.318158              0.326439   
skin_rash             0.318158   1.000000              0.298143   
nodal_skin_eruptions  0.326439   0.298143              1.000000   
continuous_sneezing  -0.086906  -0.094786             -0.032566   
shivering            -0.059893  -0.065324             -0.022444   
...                        ...        ...                   ...   
small_dents_in_nails -0.061573   0.331087             -0.023073   
inflammatory_nails   -0.061573   0.331087             -0.023073   
blister              -0.061573   0.331087             -0.023073   
red_sore_around_nose -0.061573   0.331087             -0.023073   
yellow_crust_ooze    -0.061573   0.331087             -0.023073   

                      continuous_sneezing  shivering    chills  joint_pain  \
itching                         -0.086906  -0.059893 -0.175905   -0.160650   
skin_rash                       -0.094786  -0.065324 -0.029324    0.171134   
nodal_skin_eruptions            -0.032566  -0.022444 -0.065917   -0.060200   
continuous_sneezing              1.000000   0.608981  0.446238   -0.087351   
shivering                        0.608981   1.000000  0.295332   -0.060200   
...                                   ...        ...       ...         ...   
small_dents_in_nails            -0.033480  -0.023073 -0.067765    0.359845   
inflammatory_nails              -0.033480  -0.023073 -0.067765    0.359845   
blister                         -0.033480  -0.023073 -0.067765   -0.061889   
red_sore_around_nose            -0.033480  -0.023073 -0.067765   -0.061889   
yellow_crust_ooze               -0.033480  -0.023073 -0.067765   -0.061889   

                      stomach_pain   acidity  ulcers_on_tongue  ...  \
itching                   0.202850 -0.086906         -0.059893  ...   
skin_rash                 0.161784 -0.094786         -0.065324  ...   
nodal_skin_eruptions     -0.032566 -0.032566         -0.022444  ...   
continuous_sneezing      -0.047254 -0.047254         -0.032566  ...   
shivering                -0.032566 -0.032566         -0.022444  ...   
...                            ...       ...               ...  ...   
small_dents_in_nails     -0.033480 -0.033480         -0.023073  ...   
inflammatory_nails       -0.033480 -0.033480         -0.023073  ...   
blister                  -0.033480 -0.033480         -0.023073  ...   
red_sore_around_nose     -0.033480 -0.033480         -0.023073  ...   
yellow_crust_ooze        -0.033480 -0.033480         -0.023073  ...   

                      pus_filled_pimples  blackheads  scurring  skin_peeling  \
itching                        -0.059893   -0.059893 -0.059893     -0.061573   
skin_rash                       0.320859    0.320859  0.320859      0.331087   
nodal_skin_eruptions           -0.022444   -0.022444 -0.022444     -0.023073   
continuous_sneezing            -0.032566   -0.032566 -0.032566     -0.033480   
shivering                      -0.022444   -0.022444 -0.022444     -0.023073   
...                                  ...         ...       ...           ...   
small_dents_in_nails           -0.023073   -0.023073 -0.023073      0.946120   
inflammatory_nails             -0.023073   -0.023073 -0.023073      0.946120   
blister                        -0.023073   -0.023073 -0.023073     -0.023720   
red_sore_around_nose           -0.023073   -0.023073 -0.023073     -0.023720   
yellow_crust_ooze              -0.023073   -0.023073 -0.023073     -0.023720   

                      silver_like_dusting  small_dents_in_nails  \
itching                         -0.061573             -0.061573   
skin_rash                        0.331087              0.331087   
nodal_skin_eruptions            -0.023073             -0.023073   
continuous_sneezing             -0.033480             -0.033480   
shivering                       -0.023073             -0.023073   
...                                   ...                   ...  

In [10]:
disease.nunique()

itching                  2
skin_rash                2
nodal_skin_eruptions     2
continuous_sneezing      2
shivering                2
                        ..
inflammatory_nails       2
blister                  2
red_sore_around_nose     2
yellow_crust_ooze        2
prognosis               41
Length: 133, dtype: int64

In [11]:
disease.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [12]:
y = disease['prognosis']

In [13]:
x = disease[['itching','skin_rash','continuous_sneezing','shivering','chills','joint_pain','stomach_pain','acidity','ulcers_on_tongue','blackheads','scurring','skin_peeling','silver_like_dusting','small_dents_in_nails','inflammatory_nails','blister','red_sore_around_nose','yellow_crust_ooze','nodal_skin_eruptions']]

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x,y, train_size=0.7, random_state=2529)

In [16]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3444, 19), (1476, 19), (3444,), (1476,))

In [17]:
x_train

itching  skin_rash  continuous_sneezing  shivering  chills  joint_pain  \
3884        0          0                    0          0       0           0   
244         0          0                    0          0       0           0   
4109        0          0                    0          0       0           0   
221         0          0                    0          0       0           0   
1900        0          0                    1          0       1           0   
...       ...        ...                  ...        ...     ...         ...   
4590        0          1                    0          0       0           1   
4476        0          0                    0          0       0           0   
3656        0          0                    0          0       0           0   
4836        0          1                    0          0       0           1   
2876        0          0                    0          0       0           0   

      stomach_pain  acidity  ulcers_on_tongue  blackheads  scurring  \
3884             0        0                 0           0         0   
244              0        0                 0           0         0   
4109             0        0                 0           0         0   
221              0        0                 0           0         0   
1900             0        0                 0           0         0   
...            ...      ...               ...         ...       ...   
4590             0        0                 0           0         0   
4476             0        0                 0           0         0   
3656             0        0                 0           0         0   
4836             0        0                 0           0         0   
2876             0        0                 0           0         0   

      skin_peeling  silver_like_dusting  small_dents_in_nails  \
3884             0                    0                     0   
244              0                    0                     0   
4109             0                    0                     0   
221              0                    0                     0   
1900             0                    0                     0   
...            ...                  ...                   ...   
4590             1                    1                     1   
4476             0                    0                     0   
3656             0                    0                     0   
4836             1                    1                     1   
2876             0                    0                     0   

      inflammatory_nails  blister  red_sore_around_nose  yellow_crust_ooze  \
3884                   0        0                     0                  0   
244                    0        0                     0                  0   
4109                   0        0                     0                  0   
221                    0        0                     0                  0   
1900                   0        0                     0                  0   
...                  ...      ...                   ...                ...   
4590                   1        0                     0                  0   
4476                   0        0                     0                  0   
3656                   0        0                     0                  0   
4836                   1        0                     0                  0   
2876                   0        0                     0                  0   

      nodal_skin_eruptions  
3884                     0  
244                      0  
4109                     0  
221                      0  
1900                     0  
...                    ...  
4590                     0  
4476                     0  
3656                     0  
4836                     0  
2876                     0  

[3444 rows x 19 columns]

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
lr = LogisticRegression()

In [20]:
lr.fit(x_train, y_train)

LogisticRegression()

In [21]:
y_pred = lr.predict(x_test)

In [22]:
y_pred.shape

(1476,)

In [23]:
y_pred

array(['Hepatitis E', 'Allergy', 'Typhoid', ..., 'Peptic ulcer diseae',
       'Peptic ulcer diseae', 'Peptic ulcer diseae'], dtype=object)

In [24]:
lr.predict_proba(x_test)

array([[3.43633492e-03, 3.32215199e-03, 3.93523459e-04, ...,
        3.28267784e-03, 3.36090164e-03, 2.31443413e-01],
       [5.77444774e-05, 5.66132600e-05, 9.70184259e-06, ...,
        5.62090234e-05, 5.70035096e-05, 1.28617081e-05],
       [3.74533161e-03, 3.62705809e-03, 4.97798557e-04, ...,
        3.58614446e-03, 3.66720780e-03, 6.71928357e-04],
       ...,
       [5.11543737e-02, 4.76146307e-02, 2.40479855e-03, ...,
        4.64358656e-02, 4.87939876e-02, 5.79090333e-03],
       [5.11543737e-02, 4.76146307e-02, 2.40479855e-03, ...,
        4.64358656e-02, 4.87939876e-02, 5.79090333e-03],
       [5.11543737e-02, 4.76146307e-02, 2.40479855e-03, ...,
        4.64358656e-02, 4.87939876e-02, 5.79090333e-03]])

In [25]:
pip install scipy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [26]:
pip install sklearn.metrics

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement sklearn.metrics (from versions: none)
ERROR: No matching distribution found for sklearn.metrics


In [27]:
from sklearn.ensemble import AdaBoostRegressor

In [28]:
from sklearn.metrics import confusion_matrix, classification_report

In [29]:
print(confusion_matrix(y_test, y_pred))

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 35 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [30]:
print(classification_report(y_test, y_pred))

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       0.00      0.00      0.00        31
                                   AIDS       0.00      0.00      0.00        37
                                   Acne       1.00      1.00      1.00        35
                    Alcoholic hepatitis       0.00      0.00      0.00        40
                                Allergy       1.00      0.92      0.96        37
                              Arthritis       0.00      0.00      0.00        46
                       Bronchial Asthma       0.00      0.00      0.00        37
                   Cervical spondylosis       0.00      0.00      0.00        31
                            Chicken pox       0.76      0.97      0.85        29
                    Chronic cholestasis       0.27      0.91      0.41        32
                            Common Cold       0.92      0.92      0.92        39
                           

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [31]:
x_new = disease.sample(1)

In [32]:
x_new

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
1107        0          0                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
1107          0       0           0             0        0                 0   

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
1107  ...           0         0             0                    0   

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
1107                     0                   0        0                     0   

      yellow_crust_ooze                     prognosis  
1107                  0  Dimorphic hemmorhoids(piles)  

[1 rows x 133 columns]

In [33]:
x_new.shape

(1, 133)

In [34]:
x_new = x_new.drop('prognosis', axis = 1)

In [35]:
x_new

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
1107        0          0                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
1107          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
1107  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
1107                    0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
1107                     0                  0  

[1 rows x 132 columns]

In [36]:
x_new.shape

(1, 132)

In [37]:
x_new.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
1107        0          0                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
1107          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
1107  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
1107                    0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
1107                     0                  0  

[1 rows x 132 columns]

In [38]:
from sklearn.preprocessing import MinMaxScaler

In [39]:
mm = MinMaxScaler()

In [40]:
x = mm.fit_transform(x)

In [41]:
x

array([[1., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 1., 0.]])

In [42]:
x_new = mm.fit_transform(x_new)

In [43]:
y_pred = lr.predict(x_test)

In [44]:
y_pred.shape

(1476,)

In [45]:
y_pred

array(['Hepatitis E', 'Allergy', 'Typhoid', ..., 'Peptic ulcer diseae',
       'Peptic ulcer diseae', 'Peptic ulcer diseae'], dtype=object)

In [46]:
lr.predict_proba(x_test)

array([[3.43633492e-03, 3.32215199e-03, 3.93523459e-04, ...,
        3.28267784e-03, 3.36090164e-03, 2.31443413e-01],
       [5.77444774e-05, 5.66132600e-05, 9.70184259e-06, ...,
        5.62090234e-05, 5.70035096e-05, 1.28617081e-05],
       [3.74533161e-03, 3.62705809e-03, 4.97798557e-04, ...,
        3.58614446e-03, 3.66720780e-03, 6.71928357e-04],
       ...,
       [5.11543737e-02, 4.76146307e-02, 2.40479855e-03, ...,
        4.64358656e-02, 4.87939876e-02, 5.79090333e-03],
       [5.11543737e-02, 4.76146307e-02, 2.40479855e-03, ...,
        4.64358656e-02, 4.87939876e-02, 5.79090333e-03],
       [5.11543737e-02, 4.76146307e-02, 2.40479855e-03, ...,
        4.64358656e-02, 4.87939876e-02, 5.79090333e-03]])

In [47]:
x_new

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])